const translations = {
  ar: {
    "title": "م /احمد إبراهيم لأنظمة الطاقة الشمسيه",
    "nav-home": "الصفحة الرئيسية",
    "nav-about": "نبذة عنا",
    "nav-services": "خدماتنا",
    "nav-works": "الإنجازات",
    "nav-values": "القيم",
    "nav-team": "فريق العمل",
    "nav-contact": "تواصل معنا",
    "welcome": "اهلا بكم",
    "company-name": "شركه م/ احمد ابراهيم",
    "company-sector": "لانظمه الطاقه الشمسيه",
    "about-heading": "شركة م /أحمد إبراهيم :",
    "about-subheading": "بداية الشركة كانت 2015",
    "about-title": "نبذة عن الشركة:",
    "about-point1": "شركة متخصصة في توريد وتركيب جميع أنظمة الطاقة الشمسية في جميع محافظات جمهورية مصر العربية",
    "about-point2": "حيث قامت بتنفيذ مشاريع كثيرة منذ 2015 لتشغيل الابار وتعمل في كافة القطاعات مثل القطاع الزراعي والصناعي والسكني",
    "about-point3": "الشركة مسجلة بمستندات قانونية من سجل تجاري وبطاقة ضربية",
    "about-point4": "س.ت:100450",
    "about-point5": "ب.ض: 814-710-763",
    "services-title": "الخدمات التي تقدمها الشركة",
    "service1":"توريد وتركيب محطات الطاقة الشمسية وعمل صيانات دورية للمحطات",
    "service2":"من خلالنا توريد قطعة المحطات ورفع كفاءة محطات ثم تركيبها عن طريق شركات اخرى",
    "service3": "متابعه دورية لعملائنا ما بعد التركيب  وضمان رضاهم عن الخدمه",
    "works-title": "انجازات الشركه",
    "works-subtitle": "نقدم خدمات احترافيه",
    "work1-title": "محطة 150 كيلو وات في ارض الفرافره للأستاذ:",
    "work1-text": "عماد فرفور والاستاذ علاء الضبع",
    "work2-title": "محطه 125 حصان امتداد طريق ابناء الغربيه بجوار الوطنيه:",
    "work2-text": "للدواجن للعمده بسيوني",
    "work3-title": "محطة 107 كيلو وات في الضبعه للاستاذه:",
    "work3-text": "عاشور الديب",
    "work4-title": "محطة 60 كيلو وات في مدخل شجاعه طريق العلمين للأستاذ:",
    "work4-text": "احمد عبد الرحمن (شركه القائد)",
    "work5-title": "محطه 50 كيلو وات في منطقه الروابي الخضر بالبحيره للأستاذ:",
    "work5-text": "طارق البلتاجي",
    "work6-title": "محطة بقدرة 180 كيلو وات بمدينه السادات",
    "work6-text": "محافظه المنوفيه (متحركه)",
    "work7-title": "محطة بقدرة 90 كيلو وات طريق وادي النطرون العلمين",
    "work7-text": "مزرعه نبع البركه",
    "work-link": "اذهب للمزيد",  "values-title": "قيم الشركه",
    "values-subtitle": "الضمانات المقدمه من الشركه:",
    "value1": "مراقبه الجوده اولويه قصوى للشركه وكفاءه المنتجات والتركيبات خاضعه لعمليات تفتيش",
    "value2": "صارمه للتاكد من انها تلبي اعلى معايير الجوده والصناعه في هذا المجال",

    "team-title": "فريق العمل",
    "team1": "الشركه لديها فريق عمل من المهندسين والفني وخدمه العملاء لديهم خبره واسعه في مجال الطاقه الشمسيه وعلى راسهم مهندس احمد إبراهيم",
    "team2": "نحن نعمل بجميع منتجات الطاقه من الواح وشاسيهات وانفرتارات والواح حمايات",
    "team3": "ونحن نعمل دراسه كامله لكل محطه خاصه بها وليس تطبيق كل المحطات بنفس المكونات والانواع نضع كل نوع <br>في المحطة المناسب لها",
   " team4": "دراسه جدوى كامله للمكان و موقع المحطه لتحديد الانواع والقدرات المناسبه",
    "team5": "لدينا فريق كامل من خدمه العملاء ذو الخبره الفائقه في هذا المجال لافاده العملاء على اكمل وجه وارضائهم",
    "note": "تنويه :",
    "note-text": "لكل محطه دراسه خاصه بها",

    "contact-title": "تواصل معنا",
     "work-card-1-title": "محطه بقدرة 100 كيلو وات طريق مصر اسكندريه الزراعي",
      "work-card-1-text": "محافظه الغربيه مصنع الأستاذ: احمد عايد (مصنع المراعي)",
      "work-card-2-title": "محطة بقدرة 90 كيلو وات طريق وادي النطرون العلمين",
      "work-card-2-text": "مزرعه نبع البركه",
      "work-card-3-title": ". محطه بقدره 25 كيلو وات (متحركه) بمدينه العلمين",
      "work-card-3-text": "للأستاذ: حسن عبد العليم",
      "work-card-4-title": "محطه أستاذ: سيد الشبراوي في سيناء",
      "work-card-5-title": ". محطه قدرتها 105 ونص كيلو وات مع توفير مكونات البئر خلال شهر ابريل 2025",
      "work-card-6-title": "محطه أستاذ: سيد الشبراوي في سيناء بئر العبد",
      "work-card-7-title": "محطه أستاذ: بويد بمطروح",
      "work-card-8-title": "محطه الأستاذ: عطيوة الفقي بمطروح",
      "work-card-9-title": "محطه الأستاذ: عاشور ادريس بمطروح",
      "work-card-10-title": "محطه الأستاذ: ابراهيم كتكت بطنطا",
      "work-card-11-title": ". محطه الأستاذ: رضا البري بزفتي",
      "work-card-12-title": ". محطه الأستاذ: ابو العلا السباعي",
      "work-card-13-title": ". محطه الكابتن: محمد محسن بالمنوفية",
      "work-card-14-title": ". محطة الاستاذ: طلعت شومان محطة بقدرة 75 كيلو وات اون جريد لمصنع بكفر الزيات خلال شهر مايو"
 
  },
  en: {
    "title": "Eng/Ahmed Ibrahim Solar Energy Systems",
    "nav-home": "Home",
    "nav-about": "About",
    "nav-services": "Services",
    "nav-works": "Projects",
    "nav-values": "Our Values",
    "nav-team": "Team",
    "nav-contact": "Contact Us",
    "welcome": "Welcome",
    "company-name": "Eng/Ahmed Ibrahim Company",
    "company-sector": "Solar Energy Systems",
    "about-heading": "Eng/Ahmed Ibrahim Company:",
    "about-subheading": "The company started in 2015",
    "about-title": "About the Company:",
    "about-point1": "A company specialized in supplying and installing all solar energy systems in all Egyptian governorates",
    "about-point2": "Implemented many projects since 2015 for well operations and works in agricultural, industrial, and residential sectors",
    "about-point3": "The company is officially registered with legal documents (commercial registry and tax card)",
    "about-point4": "C.R: 100450",
    "about-point5": "T.I.N: 814-710-763",
    "services-title": "Services Provided by the Company",
    "service1": "Supplying and installing solar power stations and performing regular maintenance",
    "service2": "Supplying station parts and improving efficiency, then installation by other companies",
    "service3": "Regular follow-up with our clients after installation and ensuring their satisfaction",  "works-title": "انجازات الشركه",
    
    "works-title": "Company Achievements",
    "works-subtitle": "We offer professional services",
    "work1-title": "150 kW station in Farafra land for:",
    "work1-text": "Emad Farfour and Alaa El-Dabaa",
    "work2-title": "125 HP station near National Road, Sons of Gharbia:",
    "work2-text": "For poultry, El-Omda Basyouni",
    "work3-title": "107 kW station in El-Dabaa for:",
    "work3-text": "Ashour El-Deeb",
    "work4-title": "60 kW station at Shogaa entrance, Alamein Road for:",
    "work4-text": "Ahmed Abdelrahman (El-Kaed Company)",
    "work5-title": "50 kW station in El-Rawabi El-Khadraa, Beheira for:",
    "work5-text": "Tarek El-Beltagy",
    "work6-title": "180 kW mobile station in Sadat City",
    "work6-text": "Menoufia Governorate ()",
    "work7-title": "90 kW station in Wadi El-Natrun - Alamein Road",
    "work7-text": "Naba El-Baraka Farm",
    "work-link": "Go somewhere",
    "values-title": "Company Values",
    "values-subtitle": "Company Guarantees:",
    "value1": "Quality control is a top priority; products and installations undergo inspection processes",
    "value2": "Strict checks to ensure they meet the highest quality and industry standards",

    "team-title": "Our Team",
    "team1": "Our company has a team of engineers, technicians, and customer service professionals with extensive experience in solar energy, led by Eng. Ahmed Ibrahim",
    "team2": "We work with all types of solar products including panels, frames, inverters, and protection boards",
    "team3": "We conduct full feasibility studies tailored to each station and don’t use a one-size-fits-all approach",
    "team4": "Complete site and station feasibility analysis to choose the right type and capacity",
    "team5": "Our customer service team is highly experienced and aims to fully satisfy client needs",
    "note": "Note:",
    "note-text": "Each station has its own dedicated study",

    "contact-title": "Contact Us",
      "work-card-1-title": "100 kW Station – Cairo-Alex Desert Road",
      "work-card-1-text": "El Gharbia Governorate – Mr. Ahmed Ayed (Al Marai Factory)",
      "work-card-2-title": "90 kW Station – Wadi El Natrun Alamein Road",
      "work-card-2-text": "Naba'a Al Baraka Farm",
      "work-card-3-title": "25 kW Mobile Station – El Alamein City",
      "work-card-3-text": "For Mr. Hassan Abdel Aleem",
      "work-card-4-title": "Mr. Sayed El Shabrawy Station – Sinai",
      "work-card-5-title": "105.5 kW Station with Well Components – April 2025",
      "work-card-6-title": "Mr. Sayed El Shabrawy Station – Bir El Abd, Sinai",
      "work-card-7-title": "Mr. Boyd Station – Matrouh",
      "work-card-8-title": "Mr. Atiya El Feki Station – Matrouh",
      "work-card-9-title": "Mr. Ashour Idris Station – Matrouh",
      "work-card-10-title": "Mr. Ibrahim Katkat Station – Tanta",
      "work-card-11-title": "Mr. Reda El Bary Station – Zefta",
      "work-card-12-title": "Mr. Abou El Ala El Sebaey Station",
      "work-card-13-title": "Captain Mohamed Mohsen Station – Menoufia",
      "work-card-14-title": "Mr. Talaat Shoman 75 kW On-Grid Station – Kafr El Zayat, May",
  }
  };


function setLanguage(lang) {
  const elements = document.querySelectorAll("[data-translate]");
  elements.forEach(el => {
    const key = el.getAttribute("data-translate");
    if (translations[lang][key]) {
      el.textContent = translations[lang][key];
    }
  });


  document.documentElement.lang = lang;
  document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  localStorage.setItem("lang", lang);
}

window.addEventListener("DOMContentLoaded", () => {
  setLanguage("ar");
});

